version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5433:5432"
    volumes:
       - ./migration/docker-database-initial.sql:/docker-entrypoint-initdb.d/docker-database-initial.sql
    


  pgadmin-compose:
      image: dpage/pgadmin4
      environment:
        - PGADMIN_DEFAULT_EMAIL=eletricamat@gmail.com
        - PGADMIN_DEFAULT_PASSWORD=admin
      ports:
        - "54321:80"
      depends_on:
        - postgres
